### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte

### ISSUE THREAD

**Issue by mophawka** [MZommer/LYNTml#3]
E:\content\src>Deserializer.py
(Beauty)fff2995f.bin
Traceback (most recent call last):
  File "E:\content\src\Deserializer.py", line 18, in <module>
    tml.Deserialize("./input/" + file)
  File "E:\content\src\LYN\LynTML.py", line 142, in Deserialize
    self.__parseTimeLines()
  File "E:\content\src\LYN\LynTML.py", line 217, in __parseTimeLines
    self.keyResolver(key)(key, _sizeOf, layerID, itemCount)
  File "E:\content\src\LYN\LynTML.py", line 318, in __parseLyrics
    text = self.binaryReader.string(isLYN=True).encode("utf-8").decode("utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\content\src\LYN\BinaryReader.py", line 76, in string
    arr[index] = bytearray.fromhex(i[:2]).decode() + i[2:]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte

Would appreciate some feedback on this error. 
BinaryFinder.py yielded many results but most of those give this error. What am i doing wrong?

Thank you

Edit:

Tried the dev branch and got this.
E:\content\LYNTml-dev>Deserializer.py
Traceback (most recent call last):
  File "E:\content\LYNTml-dev\Deserializer.py", line 1, in <module>
    from LYN.LynTML import LynTML
ModuleNotFoundError: No module named 'LYN.LynTML'

Thanks

**Comment by mophawka** [comment]
any help with this?

Thanks

**Comment by alexo310** [comment]
use the main branch to get the binary files and use the dev branch to deserialize it.

**Comment by mophawka** [comment]
Thanks for the info. Already fixed the issues with dev back in April. forgot all about this GHi. 

Will close this now.
